language: node_js
node_js:
  - lts/*

before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv
  -in .env.enc -out .env -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -e "ssh -o StrictHostKeyChecking=no" -r --quiet . appuser@$SERVER_IP:/home/appuser/webapp
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: ssh -o StrictHostKeyChecking=no appuser@$SERVER_IP 'bash ./deploy.sh'
  on:
    branch: master
